- hosts: daskRH7
  vars:
    custom_repo: true
    java_link: https://drive.google.com/open?id=1bSq7I3MY3SvY4MHfowEyNq3l-sFMJa8B
    flink_archive: https://www.apache.org/dyn/closer.lua/flink/flink-1.7.1/flink-1.7.1-bin-hadoop28-scala_2.11.tgz
    java_archive: jdk-8u201-linux-x64.tar.gz
    download_url: https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz
    path_base: /usr/local/java
    path_archive: /usr/local/java/{{ java_archive }} 
  become: yes 
  become_method: sudo
# pre_tasks:
#   - name: register RHEL7.5
#     command: "/usr/bin/subscription-manager register --username <name> --password <password> --auto-attach"
  tasks:
    - name: install libselinux-python
      yum:
        name: libselinux-python
        state: present
    - name: download epel
      shell:  wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -O /tmp/epel-release-latest-7.noarch.rpm
    - name: Install epel
      shell:  yum -y localinstall /tmp/epel*rpm
    - name: Install python-pip
      yum:
        name: python-pip
        state: latest
    - name: install dask
      shell: pip install "dask[complete]"
# post_tasks:
#   - name: Install texlive
#     yum:
#       name: texlive
#       state: present
#   - name: remove RHEL7.5
#     command:  "/usr/bin/subscription-manager remove --all"
#   - name: unregister RHEL7.5
#     command:  "/usr/bin/subscription-manager unregister"
#   - name: clean RHEL7.5
#     command:  "/usr/bin/subscription-manager clean"
